[master]
scada-master ansible_host=192.168.56.10 ansible_user=vagrant ansible_ssh_private_key_file=vagrant/.vagrant/machines/scada-master/virtualbox/private_key

[workers]
scada-worker-1 ansible_host=192.168.56.11 ansible_user=vagrant ansible_ssh_private_key_file=vagrant/.vagrant/machines/scada-worker-1/virtualbox/private_key
scada-worker-2 ansible_host=192.168.56.12 ansible_user=vagrant ansible_ssh_private_key_file=vagrant/.vagrant/machines/scada-worker-2/virtualbox/private_key

[scada:children]
master
workers

[scada:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
