[master]
scada-master ansible_host=10.136.138.187 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[workers]
scada-worker-1 ansible_host=10.136.138.254 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa
scada-worker-2 ansible_host=10.136.138.205 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/id_rsa

[scada:children]
master
workers

[scada:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null'
