---
scada_base_dir: /opt/scada
grafana_port: 3000
nodered_port: 1880
influxdb_port: 8086
mosquitto_port: 1883
mosquitto_ws_port: 9001
influxdb_version: "2.7"
grafana_image: "grafana/grafana:latest"
nodered_image: "nodered/node-red:latest"
mosquitto_image: "eclipse-mosquitto:2"
influxdb_image: "influxdb:2.7"
